### ISSUE TITLE
Replace tokio mutex with std mutex

### ISSUE THREAD

**Issue by anonrig** [anonrig/pacquet#15]
@steveklabnik recommended on twitter: https://twitter.com/steveklabnik/status/1681365703163510785?s=61&t=fh15eQmorKGlcinuOnPJJQ

**Comment by steveklabnik** [comment]
This is what I wanted to link to in our Twitter discussion, but didn't realize it was posted over on mastadon https://hachyderm.io/@rain/110737366912995499
